import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MPH Field Docs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav
          className="app-nav"
          style={{
            width: '100%',
            padding: '16px 0',
            borderBottom: '1px solid #ddd',
            display: 'flex',
            justifyContent: 'center',
            gap: '32px',
            background: '#fafafa',
            fontSize: '18px',
          }}
        >
          <a href="/" style={{ textDecoration: 'none', color: '#222' }}>Home</a>
          <a href="/invoices" style={{ textDecoration: 'none', color: '#222' }}>Field Docs</a>
          <a href="/book-pages" style={{ textDecoration: 'none', color: '#222' }}>Book Pages</a>
        </nav>
        <style>{`
          @media print {
            .app-nav {
              display: none !important;
            }
          }
        `}</style>
        {children}
      </body>
    </html>
  );
}
